# Generated by Django 3.1.3 on 2020-11-27 01:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MetricSystem',
            new_name='SystemOfMeasurements',
        ),
        migrations.AlterModelOptions(
            name='systemofmeasurements',
            options={'verbose_name': 'Sistema de medidas', 'verbose_name_plural': 'Sistemas de medidas'},
        ),
        migrations.RemoveField(
            model_name='unit',
            name='metric_system',
        ),
        migrations.RemoveField(
            model_name='unit',
            name='quantity',
        ),
        migrations.AddField(
            model_name='unit',
            name='name',
            field=models.CharField(default=1, max_length=40, verbose_name='Nombre'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='unit',
            name='system_of_measurements',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='core.systemofmeasurements', verbose_name='Sistema de medidas'),
        ),
    ]
