# Generated by Django 3.1.3 on 2020-11-27 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredientserving',
            name='quantity',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Cantidad de ingrediente'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='description',
            field=models.TextField(null=True, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='ingredientserving',
            name='description',
            field=models.TextField(null=True, verbose_name='Descripción'),
        ),
    ]
