# Generated by Django 3.1.3 on 2020-11-27 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_auto_20201127_0150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='Descripción'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ingredientserving',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='Descripción'),
            preserve_default=False,
        ),
    ]
