# Generated by Django 3.1.3 on 2020-11-28 16:16

from django.db import migrations, models
import django.db.models.deletion
import recipes.models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_auto_20201127_0154'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecipeImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=recipes.models.recipe_upload_path, verbose_name='Imagen de muestra')),
                ('is_primary', models.BooleanField(verbose_name='Es la imagen de presentación?')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.recipe', verbose_name='Receta')),
            ],
        ),
    ]
